import fi.helsinki.cs.tmc.edutestutils.MockStdio;
import fi.helsinki.cs.tmc.edutestutils.Points;
import fi.helsinki.cs.tmc.edutestutils.ReflectionUtils;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;
import org.junit.*;
import static org.junit.Assert.*;

@Points("03-08")
public class OnlyTheseNumbersTest {

    @Rule
    public MockStdio io = new MockStdio();

    @Test
    public void test() {
        // Array of input scenarios, each represented as an array of strings
        String[][] input = {
            {"3", "2", "1", "4", "7", "-1", "0", "1"},
            {"3", "9", "2", "8", "-1", "2", "3"}
        };

        // Loop through each input scenario and run the check method
        for (int i = 0; i < input.length; i++) {
            check(input[i]);
        }
    }

    private void check(String... input) {
        int oldOut = io.getSysOut().length();

        // Parse lower and upper bounds from the last two elements of input array
        int lower = Integer.valueOf(input[input.length - 2]);
        int upper = Integer.valueOf(input[input.length - 1]);

        String in = "";
        List<Integer> numbers = new ArrayList<>();
        // Construct the input string and gather numbers to be printed
        for (int i = 0; i < input.length; i++) {
            in += input[i] + "\n";

            if (i < input.length - 2) {
                numbers.add(Integer.valueOf(input[i]));
            }
        }

        // Set the input for the program using MockStdio
        io.setSysIn(in);
        // Call the main method of OnlyTheseNumbers class
        callMain(OnlyTheseNumbers.class);
        // Get the output generated by the program
        String out = io.getSysOut().substring(oldOut);

        // Ensure that the program is printing something
        assertTrue("you're not printing anything!", out.length() > 0);

        // Check if numbers within the specified range are printed
        for (int i = lower; i <= upper; i++) {
            if (!out.contains("" + numbers.get(i))) {
                fail("Input:\n" + in + "\nOutput was expected to contain \"" + numbers.get(i) + "\", but it wasn't printed.\nOutput was:\n" + out);
            }
        }

        // Check if numbers outside the specified range are not printed
        NEXT:
        for (int i = 0; i < 50; i++) {
            for (int index = lower; index <= upper; index++) {
                if (numbers.get(index) == i) {
                    continue NEXT;
                }
            }
            if (out.contains("" + i)) {
                fail("Input:\n" + in + "\nOutput wasn't expected to contain number \"" + i + "\", but it was printed.\nOutput was:\n" + out);
            }
        }
    }

    private void callMain(Class kl) {
        try {
            kl = ReflectionUtils.newInstanceOfClass(kl);
            String[] t = null;
            String x[] = new String[0];
            // Get the main method of the provided class
            Method m = ReflectionUtils.requireMethod(kl, "main", x.getClass());
            // Invoke the main method with empty arguments
            ReflectionUtils.invokeMethod(Void.TYPE, m, null, (Object) x);
        } catch (NoSuchElementException e) {
            // Catch the case where the program tries to read too much input
            fail("Your program tried to read too much input. Remember to use nextLine() method to read!");
        } catch (Throwable e) {
            // Catch any other unexpected errors during program execution
            fail("Something unexpected happened. The public static void main(String[] args) method of '" + kl + "' class has disappeared \n"
            + "or something unexpected happened. More info: " + e);
        }
    }

    private static String[] getLastWords(String inputStr) {
        String[] parts = inputStr.split("\\s+");
        return new String[]{parts[parts.length - 2], parts[parts.length - 1]};
    }
}
