import fi.helsinki.cs.tmc.edutestutils.MockStdio;
import fi.helsinki.cs.tmc.edutestutils.Points;
import fi.helsinki.cs.tmc.edutestutils.ReflectionUtils;
import java.lang.reflect.Method;
import java.util.NoSuchElementException;
import org.junit.*;
import static org.junit.Assert.*;

@Points("03-14")
public class OnTheListTest {

    @Rule
    public MockStdio io = new MockStdio();

    @Test
    public void test() {
        // Array of input scenarios, each represented as an array of strings
        String[][] inputs = {
            {"Thomas", "Elizabeth", "Alex", "Mary", ""},
            {"Elizabeth", "Alex", "Mary", ""},
            {"First", "Second", "Third", "Fourth", "Fifth", "Sixth", "Seventh", ""}
        };

        // Loop through each input scenario and run the check method for different search names
        for (int i = 0; i < inputs.length; i++) {
            check("Nonexistent", inputs[i]);
            check("Elizabeth", inputs[i]);
            check("Mary", inputs[i]);
        }
    }

    private void check(String searching, String... strings) {
        int oldOut = io.getSysOut().length();

        String in = "";
        boolean found = false;
        // Construct the input string and determine if the searching name is found
        for (int i = 0; i < strings.length; i++) {
            in += strings[i] + "\n";
            if (strings[i].equals(searching)) {
                found = true;
            }
        }

        // Add the searching name to the input string
        in += searching + "\n";

        // Set the input for the program using MockStdio
        io.setSysIn(in);
        // Call the main method of OnTheList class
        callMain(OnTheList.class);
        // Get the output generated by the program
        String out = io.getSysOut().substring(oldOut);

        // Ensure that the program is printing something
        assertTrue("you aren't printing anything!", out.length() > 0);

        // Check the output based on whether the name was found or not
        if (found) {
            // Assertions for the case when the name is found
            assertTrue("When the person is found, the output should contain the name.\nFor example: \"Thomas was found!\".\nNow the output was:\n" + out, out.contains(searching));
            assertTrue("When the person is found, the output should say \"found\".\nFor example: \"Thomas was found!\".\nNow the output was:\n" + out, out.contains("was found"));
            assertFalse("When the person is found, the output should not contain \"was not found\".\nFor example: \"Arto was not found!\".\nNow the output was:\n" + out, out.contains("not"));
        } else {
            // Assertions for the case when the name is not found
            assertTrue("When the person is not found, the output should contain the name.\nFor example: \"Thomas was not found!\".\nNow the output was:\n" + out, out.contains(searching));
            assertFalse("When the person is not found, the output should not contain \"was found\".\nNow the output was:\n" + out, out.contains("was f"));
            assertTrue("When the person is not found, the output should contain \"was not found\".\nFor example: \"Arto was not found!\".\nNow the output was:\n" + out, out.contains("not"));
        }
    }

    private void callMain(Class kl) {
        try {
            kl = ReflectionUtils.newInstanceOfClass(kl);
            String[] t = null;
            String x[] = new String[0];
            // Get the main method of the provided class
            Method m = ReflectionUtils.requireMethod(kl, "main", x.getClass());
            // Invoke the main method with empty arguments
            ReflectionUtils.invokeMethod(Void.TYPE, m, null, (Object) x);
        } catch (NoSuchElementException e) {
            // Catch the case where the program tries to read too much input
            fail("Your program tried to read too much input. Remember to use nextLine() method to read!");
        } catch (Throwable e) {
            // Catch any other unexpected errors during program execution
            fail("Something unexpected happened. The public static void main(String[] args) method of '" + kl + "' class has disappeared \n"
            + "or something unexpected happened. More info: " + e);
        }
    }
}
